apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-map
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: otus
      volumes:
        - name: otus
          persistentVolumeClaim:
            claimName: postgres-persistent-claim